#!/usr/bin/python3
import sys

def factorize_number():
    """
    Function to read a file, extract numbers, and format them as n = p * q.
    """
    try:
        input_file = sys.argv[1]
        with open(input_file) as file:
            for number_str in file:
                number = int(number_str)
                if number % 2 == 0:
                    print("{}={}*{}".format(number, number // 2, 2))
                    continue
                divisor = 3
                while divisor < number // 2:
                    if number % divisor == 0:
                        print("{}={}*{}".format(number, number // divisor, divisor))
                        break
                    divisor = divisor + 2
                if divisor == (number // 2) + 1:
                    print("{}={}*{}".format(number, number, 1))
    except IndexError:
        pass

# Autostart
factorize_number()

